### ISSUE TITLE
[Help]: inference the model of  vall-e  report error

### ISSUE THREAD

**Issue by fangbingxiao** [open-mmlab/Amphion#134]
the report error is :

subprocess.CalledProcessError: Command '['/data/gpu_env_common/env/anaconda3/envs/whisper_valle_fang/bin/python3.9', '/data/bingxiao.fang/txt_to_speech/Amphion/bins/tts/inference.py', '--config', 'ckpts/tts/valle_libritts/args.json', '--log_level', 'debug', '--acoustics_dir', 'ckpts/tts/valle_libritts', '--output_dir', 'ckpts/tts/valle_libritts/result', '--mode', 'single', '--text', 'This is a clip of generated speech with the given text from Amphion Vall-E model.', '--text_prompt', 'But even the unsuccessful dramatist has his moments.', '--audio_prompt', 'egs/tts/VALLE/prompt_examples/7176_92135_000004_000000.wav', '--test_list_file', 'None']' died with <Signals.SIGSEGV: 11>.

**Comment by HarryHe11** [comment]
Hi @fangbingxiao, thank you for bringing this issue to our attention. However, the error information provided is a bit too vague for us to offer effective assistance. Could you please share a more detailed error traceback and some context about your experiment?

**Comment by lmxue** [comment]
Hi @fangbingxiao, my friend also encountered this problem yesterday. She sent me the log and I checked it. 

A SIGSEGV signal, represented by <Signals.SIGSEGV: 11>, indicates a segmentation fault has occurred. This is a type of error caused by a program trying to read or write an illegal memory location. It's a common critical error that leads to a program crash.

Therefore, you can check if there's enough memory available on your system. Insufficient memory might lead to segmentation faults, especially when working with large models or datasets.

**Comment by RMSnow** [comment]
Hi @fangbingxiao, if you have any further questions, feel free to re-open this issue. We are glad to follow up!
