### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Amphion/ckpts/svc/exp2/singers.json' when running SVC stage 3

### ISSUE THREAD

**Issue by lcc-404** [open-mmlab/Amphion#59]
I followed the SVC recipe and got this error in stage 3,but I'm sure the singers.json is in the right directory.
Is there a problem about path within my script?

**Comment by Adorable-Qin** [comment]
Hi @lcc-404!
I think it's because the script is being executed in the wrong path in the terminal.
According to the error, what you used is a relative path. You need to make sure that the location where you execute the script is able to access the `Amphion` directory.
Or just use an absolute path like `~/{something you made}/Amphion/ckpts/svc/exp2/singers.json`. You can use the `pwd` command to get the absolute path of where you are.
If the problem still exists, could you please provide us with more detailed error messages in the terminal?

**Comment by Adorable-Qin** [comment]
Hi @lcc-404 !

I have tried to reproduce your problem. I noticed that the default address used in the script is a relative path. If you change the directory of the Amphion or the path in the terminal does not match, FileNotFoundError will be thrown.

You could replace the path in the script with an absolute path and it would work fine.

If you have any other questions, feel free to reopen the issue and we will be glad to help.
